version: '3.8'
services:
  tomcat:
    image: tomcat:9.0.96-jdk17
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres  # Nombre del servicio de PostgreSQL en la red de Docker
      - DB_PORT=5432
    depends_on:
      - postgres
    volumes:
      # Asegúrate de ajustar la ruta a tu archivo .war local
      - ./target/GR05_1BT3_622_24A-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/GR05_1BT3_622_24A.war

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres      # Cambia a tu usuario de PostgreSQL
      POSTGRES_PASSWORD: usuario  # Cambia a tu contraseña de PostgreSQL
      POSTGRES_DB: LasHuequitas        # Cambia al nombre de tu base de datos
    ports:
      - "5432:5432"
